### ISSUE TITLE
Ulimited number of widgets

### ISSUE THREAD

**Issue by testcocoon** [lposidon/posidonLauncher#6]
Actually only one widget can be selected, this limits the possibilities of this launcher.
Better would be to have the possibility to add as many as the user wants.

**Comment by ClockGen** [comment]
It'd be really nice to be able to add multiple widgets and have them scrollable up/down, together with the rest of the feed. Maybe in that case it'd be good to also add a switch to display notificationa first.

**Comment by jkc88** [comment]
Since i'm used to having a Tasks todo-widget on my home screen, this is the only feature i'm sorely missing from Posidon. I can add the widget fine but currently it isn't scrollable, making it pretty much useless. Also i lose the clock since only one widget can be added. Otherwise this seems like the best launcher i've come across, so thanks!
